version: "3"

services:
  bot:
    build: .

  grafana:
    image: grafana/grafana-oss:8.3.3
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:2.1
    container_name: influx
    volumes:
      - ./data:/root/.influxdbv2
    ports:
      - 8086:8086

volumes:
  grafana-storage:
    driver: local